application: gae-blog-go
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

- url: /admin/.*
  script: _go_app
  login: admin

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- \.gitignore
- ^\.git/.*

